# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1473964326);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 37);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1473968184023");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1473971784023");
user_pref("browser.search.countryCode", "NL");
user_pref("browser.search.region", "NL");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20160823121617");
user_pref("browser.slowStartup.averageTime", 2713);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20160823121617");
user_pref("browser.startup.homepage_override.mstone", "48.0.2");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\",\"sync-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"loop-button\",\"pocket-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"]},\"seen\":[\"loop-button\",\"pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"PanelUI-contents\",\"addon-bar\"],\"currentVersion\":6,\"newElementCount\":0}");
user_pref("browser.urlbar.daysBeforeHidingSuggestionsPrompt", 3);
user_pref("browser.urlbar.lastSuggestionsPromptDate", 20160915);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1473968191204");
user_pref("datareporting.sessions.current.activeTicks", 6);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 2185);
user_pref("datareporting.sessions.current.main", 310);
user_pref("datareporting.sessions.current.sessionRestored", 2479);
user_pref("datareporting.sessions.current.startTime", "1473968178727");
user_pref("datareporting.sessions.current.totalTime", 47);
user_pref("datareporting.sessions.currentIndex", 1);
user_pref("datareporting.sessions.previous.0", "{\"s\":1473964324587,\"a\":5,\"t\":33,\"c\":true,\"m\":324,\"fp\":2730,\"sr\":2985}");
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.push.userAgentID", "b90cd625fd634e76a114fd8a0f703b5a");
user_pref("e10s.rollout.cohort", "control");
user_pref("e10s.rollout.cohortSample", "0.731635");
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{\"e10srollout@mozilla.org\":{\"version\":\"1.1\",\"type\":\"extension\",\"descriptor\":\"/Applications/Firefox.app/Contents/Resources/browser/features/e10srollout@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"firefox@getpocket.com\":{\"version\":\"1.0.4\",\"type\":\"extension\",\"descriptor\":\"/Applications/Firefox.app/Contents/Resources/browser/features/firefox@getpocket.com.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"loop@mozilla.org\":{\"version\":\"1.4.4\",\"type\":\"extension\",\"descriptor\":\"/Applications/Firefox.app/Contents/Resources/browser/features/loop@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10sBlockedByAddons", false);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:48.0.2");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "48.0.2");
user_pref("extensions.lastPlatformVersion", "48.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-system-defaults\":{\"e10srollout@mozilla.org\":{\"d\":\"/Applications/Firefox.app/Contents/Resources/browser/features/e10srollout@mozilla.org.xpi\",\"e\":true,\"v\":\"1.1\",\"st\":1473171496000},\"firefox@getpocket.com\":{\"d\":\"/Applications/Firefox.app/Contents/Resources/browser/features/firefox@getpocket.com.xpi\",\"e\":true,\"v\":\"1.0.4\",\"st\":1473171496000},\"loop@mozilla.org\":{\"d\":\"/Applications/Firefox.app/Contents/Resources/browser/features/loop@mozilla.org.xpi\",\"e\":true,\"v\":\"1.4.4\",\"st\":1473171496000}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/Applications/Firefox.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"48.0.2\",\"st\":1473171496000}}}");
user_pref("gecko.buildID", "20160823121617");
user_pref("gecko.mstone", "48.0.2");
user_pref("gfx.blacklist.direct2d", 3);
user_pref("gfx.blacklist.direct2d.failureid", "FEATURE_FAILURE_DL_BLACKLIST_g984");
user_pref("loop.copy.ticket", 143);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1473968179);
user_pref("toolkit.telemetry.previousBuildID", "20160823121617");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
